// GitHub-style language colors
export const languageColors: { [key: string]: string } = {
  'TypeScript': '#3178c6',
  'JavaScript': '#f1e05a',
  'HTML': '#e34c26',
  'CSS': '#563d7c',
  'Python': '#3572A5',
  'Java': '#b07219',
  'C#': '#178600',
  'C++': '#f34b7d',
  'C': '#555555',
  'PHP': '#4F5D95',
  'Ruby': '#701516',
  'Go': '#00ADD8',
  'Rust': '#dea584',
  'Swift': '#ffac45',
  'Kotlin': '#F18E33',
  'Scala': '#c22d40',
  'R': '#198ce7',
  'MATLAB': '#e16737',
  'Shell': '#89e051',
  'PowerShell': '#012456',
  'Lua': '#000080',
  'Dart': '#00B4AB',
  'Elixir': '#6e4a7e',
  'Clojure': '#db5855',
  'Haskell': '#5e5086',
  'OCaml': '#3be133',
  'F#': '#b845fc',
  'Assembly': '#6E4C13',
  'Vue': '#2c3e50',
  'React': '#61dafb',
  'Angular': '#dd0031',
  'Svelte': '#ff3e00',
  'Next.js': '#000000',
  'Nuxt.js': '#00c58e',
  'Vite': '#646cff',
  'Webpack': '#8dd6f9',
  'Babel': '#f9dc3e',
  'ESLint': '#4b32c3',
  'Prettier': '#f7b93e',
  'Jest': '#c21325',
  'Cypress': '#17202c',
  'Storybook': '#ff4785',
  'Tailwind CSS': '#06b6d4',
  'Bootstrap': '#7952b3',
  'Material-UI': '#0081cb',
  'Ant Design': '#1890ff',
  'Chakra UI': '#319795',
  'Styled Components': '#db7093',
  'Sass': '#cf649a',
  'Less': '#1d365d',
  'PostCSS': '#dd3a0a',
  'GraphQL': '#e10098',
  'Apollo': '#311c87',
  'Prisma': '#2d3748',
  'MongoDB': '#47a248',
  'PostgreSQL': '#336791',
  'MySQL': '#4479a1',
  'SQLite': '#003b57',
  'Redis': '#dc382d',
  'Docker': '#2496ed',
  'Kubernetes': '#326ce5',
  'AWS': '#ff9900',
  'Azure': '#0089d6',
  'Google Cloud': '#4285f4',
  'Firebase': '#ffca28',
  'Vercel': '#000000',
  'Netlify': '#00ad9f',
  'Heroku': '#430098',
  'DigitalOcean': '#0080ff',
  'GitHub Actions': '#2088ff',
  'Travis CI': '#3eaaaf',
  'CircleCI': '#343434',
  'Jenkins': '#d33833',
  'GitLab CI': '#fc6d26',
  'Bitbucket Pipelines': '#0052cc',
  'npm': '#cb3837',
  'Yarn': '#2c8ebb',
  'pnpm': '#f69220',
  'Lerna': '#9333ea',
  'Rush': '#ff6b6b',
  'Nx': '#143055',
  'Turborepo': '#ef4444',
  'Monorepo': '#6366f1',
  'Microservices': '#10b981',
  'Serverless': '#ff6b35',
  'JAMstack': '#f0047f',
  'PWA': '#5a0fc8',
  'SPA': '#00d4aa',
  'SSR': '#ff6b6b',
  'SSG': '#8b5cf6',
  'API': '#06b6d4',
  'REST': '#ff6b35',
  'GraphQL': '#e10098',
  'gRPC': '#4285f4',
  'WebSocket': '#00d4aa',
  'WebRTC': '#ff6b6b',
  'Electron': '#47848f',
  'Tauri': '#ffc131',
  'React Native': '#61dafb',
  'Flutter': '#02569b',
  'Ionic': '#3880ff',
  'Cordova': '#34495e',
  'Capacitor': '#119eff',
  'Unity': '#000000',
  'Unreal Engine': '#313131',
  'Godot': '#478cbf',
  'Blender': '#f5792a',
  'Three.js': '#000000',
  'WebGL': '#990000',
  'Canvas': '#ff6b35',
  'SVG': '#ffb13b',
  'Web Audio': '#ff6b6b',
  'Web Workers': '#00d4aa',
  'Service Workers': '#ff6b35',
  'IndexedDB': '#4285f4',
  'LocalStorage': '#00d4aa',
  'SessionStorage': '#ff6b6b',
  'Cookies': '#ffb13b',
  'JWT': '#ff6b35',
  'OAuth': '#4285f4',
  'OpenID Connect': '#ff6b6b',
  'SAML': '#00d4aa',
  'LDAP': '#ffb13b',
  'Active Directory': '#0078d4',
  'OAuth 2.0': '#4285f4',
  'OIDC': '#ff6b6b',
  'SAML 2.0': '#00d4aa',
  'SCIM': '#ffb13b',
  'MFA': '#ff6b35',
  '2FA': '#4285f4',
  'TOTP': '#00d4aa',
  'HOTP': '#ff6b6b',
  'U2F': '#ffb13b',
  'WebAuthn': '#4285f4',
  'FIDO2': '#00d4aa',
  'Biometric': '#ff6b35',
  'Face ID': '#4285f4',
  'Touch ID': '#00d4aa',
  'Fingerprint': '#ff6b6b',
  'Iris': '#ffb13b',
  'Voice': '#4285f4',
  'Behavioral': '#00d4aa',
  'Risk-based': '#ff6b35',
  'Adaptive': '#4285f4',
  'Contextual': '#00d4aa',
  'Zero Trust': '#ff6b6b',
  'Zero Knowledge': '#ffb13b',
  'End-to-End': '#4285f4',
  'Client-Side': '#00d4aa',
  'Server-Side': '#ff6b35',
  'Edge': '#4285f4',
  'Cloud': '#00d4aa',
  'Hybrid': '#ff6b6b',
  'Multi-Cloud': '#ffb13b',
  'Polyglot': '#4285f4',
  'Micro-Frontends': '#00d4aa',
  'Module Federation': '#ff6b35',
  'Web Components': '#4285f4',
  'Custom Elements': '#00d4aa',
  'Shadow DOM': '#ff6b6b',
  'HTML Templates': '#ffb13b',
  'Progressive Enhancement': '#4285f4',
  'Graceful Degradation': '#00d4aa',
  'Feature Detection': '#ff6b35',
  'Polyfills': '#4285f4',
  'Shims': '#00d4aa',
  'Fallbacks': '#ff6b6b',
  'Graceful Fallbacks': '#ffb13b',
  'Elegant Degradation': '#4285f4',
  'Responsive Design': '#00d4aa',
  'Mobile First': '#ff6b35',
  'Desktop First': '#4285f4',
  'Adaptive Design': '#00d4aa',
  'Fluid Design': '#ff6b6b',
  'Elastic Design': '#ffb13b',
  'Liquid Design': '#4285f4',
  'Fixed Design': '#00d4aa',
  'Hybrid Design': '#ff6b35',
  'Atomic Design': '#4285f4',
  'Design Systems': '#00d4aa',
  'Component Libraries': '#ff6b6b',
  'UI Kits': '#ffb13b',
  'Design Tokens': '#4285f4',
  'Style Guides': '#00d4aa',
  'Brand Guidelines': '#ff6b35',
  'Visual Identity': '#4285f4',
  'Brand Identity': '#00d4aa',
  'Corporate Identity': '#ff6b6b',
  'Brand Strategy': '#ffb13b',
  'Brand Positioning': '#4285f4',
  'Brand Architecture': '#00d4aa',
  'Brand Portfolio': '#ff6b35',
  'Brand Extension': '#4285f4',
  'Brand Dilution': '#00d4aa',
  'Brand Equity': '#ff6b6b',
  'Brand Value': '#ffb13b',
  'Brand Recognition': '#4285f4',
  'Brand Recall': '#00d4aa',
  'Brand Awareness': '#ff6b35',
  'Brand Loyalty': '#4285f4',
  'Brand Trust': '#00d4aa',
  'Brand Reputation': '#ff6b6b',
  'Brand Image': '#ffb13b',
  'Brand Personality': '#4285f4',
  'Brand Voice': '#00d4aa',
  'Brand Tone': '#ff6b35',
  'Brand Messaging': '#4285f4',
  'Brand Communication': '#00d4aa',
  'Brand Marketing': '#ff6b6b',
  'Brand Advertising': '#ffb13b',
  'Brand Promotion': '#4285f4',
  'Brand Publicity': '#00d4aa',
  'Brand PR': '#ff6b35',
  'Brand Media': '#4285f4',
  'Brand Content': '#00d4aa',
  'Brand Storytelling': '#ff6b6b',
  'Brand Narrative': '#ffb13b',
  'Brand Story': '#4285f4',
  'Brand Journey': '#00d4aa',
  'Brand Experience': '#ff6b35',
  'Brand Touchpoints': '#4285f4',
  'Brand Interactions': '#00d4aa',
  'Brand Engagement': '#ff6b6b',
  'Brand Activation': '#ffb13b',
  'Brand Events': '#4285f4',
  'Brand Sponsorships': '#00d4aa',
  'Brand Partnerships': '#ff6b35',
  'Brand Collaborations': '#4285f4',
  'Brand Co-branding': '#00d4aa',
  'Brand Franchising': '#ff6b6b',
  'Brand Expansion': '#ffb13b',
  'Brand Growth': '#4285f4',
  'Brand Development': '#ff6b35',
  'Brand Evolution': '#4285f4',
  'Brand Transformation': '#00d4aa',
  'Brand Rebranding': '#ff6b6b',
  'Brand Refresh': '#ffb13b',
  'Brand Update': '#4285f4',
  'Brand Modernization': '#00d4aa',
  'Brand Innovation': '#ff6b35',
  'Brand Disruption': '#4285f4',
  'Brand Revolution': '#00d4aa',
  'Brand Revolution': '#ff6b6b',
  'Brand Disruption': '#ffb13b',
  'Brand Innovation': '#4285f4',
  'Brand Modernization': '#00d4aa',
  'Brand Update': '#ff6b35',
  'Brand Refresh': '#4285f4',
  'Brand Rebranding': '#00d4aa',
  'Brand Transformation': '#ff6b6b',
  'Brand Evolution': '#ffb13b',
  'Brand Development': '#4285f4',
  'Brand Growth': '#00d4aa',
  'Brand Expansion': '#ff6b35',
  'Brand Franchising': '#4285f4',
  'Brand Licensing': '#00d4aa',
  'Brand Co-branding': '#ff6b6b',
  'Brand Collaborations': '#ffb13b',
  'Brand Partnerships': '#4285f4',
  'Brand Sponsorships': '#00d4aa',
  'Brand Events': '#ff6b35',
  'Brand Activation': '#4285f4',
  'Brand Engagement': '#00d4aa',
  'Brand Interactions': '#ff6b6b',
  'Brand Touchpoints': '#ffb13b',
  'Brand Experience': '#4285f4',
  'Brand Journey': '#00d4aa',
  'Brand Story': '#ff6b35',
  'Brand Narrative': '#4285f4',
  'Brand Storytelling': '#00d4aa',
  'Brand Content': '#ff6b6b',
  'Brand Media': '#ffb13b',
  'Brand PR': '#4285f4',
  'Brand Publicity': '#00d4aa',
  'Brand Promotion': '#ff6b35',
  'Brand Advertising': '#4285f4',
  'Brand Marketing': '#00d4aa',
  'Brand Communication': '#ff6b6b',
  'Brand Messaging': '#ffb13b',
  'Brand Tone': '#4285f4',
  'Brand Voice': '#00d4aa',
  'Brand Personality': '#ff6b35',
  'Brand Image': '#4285f4',
  'Brand Reputation': '#00d4aa',
  'Brand Trust': '#ff6b6b',
  'Brand Loyalty': '#ffb13b',
  'Brand Awareness': '#4285f4',
  'Brand Recall': '#00d4aa',
  'Brand Recognition': '#ff6b35',
  'Brand Value': '#4285f4',
  'Brand Equity': '#00d4aa',
  'Brand Dilution': '#ff6b6b',
  'Brand Extension': '#ffb13b',
  'Brand Portfolio': '#4285f4',
  'Brand Architecture': '#00d4aa',
  'Brand Positioning': '#ff6b35',
  'Brand Strategy': '#4285f4',
  'Corporate Identity': '#00d4aa',
  'Brand Identity': '#ff6b6b',
  'Visual Identity': '#ffb13b',
  'Brand Guidelines': '#4285f4',
  'Style Guides': '#00d4aa',
  'Design Tokens': '#ff6b35',
  'UI Kits': '#4285f4',
  'Component Libraries': '#00d4aa',
  'Design Systems': '#ff6b6b',
  'Atomic Design': '#ffb13b',
  'Hybrid Design': '#4285f4',
  'Fixed Design': '#00d4aa',
  'Liquid Design': '#ff6b35',
  'Elastic Design': '#4285f4',
  'Fluid Design': '#00d4aa',
  'Adaptive Design': '#ff6b6b',
  'Desktop First': '#ffb13b',
  'Mobile First': '#4285f4',
  'Responsive Design': '#00d4aa',
  'Elegant Degradation': '#ff6b35',
  'Graceful Fallbacks': '#4285f4',
  'Fallbacks': '#00d4aa',
  'Shims': '#ff6b6b',
  'Polyfills': '#ffb13b',
  'Feature Detection': '#4285f4',
  'Graceful Degradation': '#00d4aa',
  'Progressive Enhancement': '#ff6b35',
  'HTML Templates': '#4285f4',
  'Shadow DOM': '#00d4aa',
  'Custom Elements': '#ff6b6b',
  'Web Components': '#ffb13b',
  'Module Federation': '#4285f4',
  'Micro-Frontends': '#00d4aa',
  'Polyglot': '#ff6b35',
  'Multi-Cloud': '#4285f4',
  'Hybrid': '#00d4aa',
  'Cloud': '#ff6b6b',
  'Edge': '#ffb13b',
  'Server-Side': '#4285f4',
  'Client-Side': '#00d4aa',
  'End-to-End': '#ff6b35',
  'Zero Knowledge': '#4285f4',
  'Zero Trust': '#00d4aa',
  'Contextual': '#ff6b6b',
  'Adaptive': '#ffb13b',
  'Risk-based': '#4285f4',
  'Behavioral': '#00d4aa',
  'Voice': '#ff6b35',
  'Iris': '#4285f4',
  'Fingerprint': '#00d4aa',
  'Touch ID': '#ff6b6b',
  'Face ID': '#ffb13b',
  'Biometric': '#4285f4',
  'FIDO2': '#00d4aa',
  'WebAuthn': '#ff6b35',
  'U2F': '#4285f4',
  'HOTP': '#00d4aa',
  'TOTP': '#ff6b6b',
  '2FA': '#ffb13b',
  'MFA': '#4285f4',
  'SCIM': '#00d4aa',
  'SAML 2.0': '#ff6b35',
  'OIDC': '#4285f4',
  'OAuth 2.0': '#00d4aa',
  'Active Directory': '#ff6b6b',
  'LDAP': '#ffb13b',
  'SAML': '#4285f4',
  'OpenID Connect': '#00d4aa',
  'OAuth': '#ff6b35',
  'JWT': '#4285f4',
  'Cookies': '#00d4aa',
  'SessionStorage': '#ff6b6b',
  'LocalStorage': '#ffb13b',
  'IndexedDB': '#4285f4',
  'Service Workers': '#00d4aa',
  'Web Workers': '#ff6b35',
  'Web Audio': '#4285f4',
  'SVG': '#00d4aa',
  'Canvas': '#ff6b6b',
  'WebGL': '#ffb13b',
  'Three.js': '#4285f4',
  'Blender': '#00d4aa',
  'Godot': '#ff6b35',
  'Unreal Engine': '#4285f4',
  'Unity': '#00d4aa',
  'Capacitor': '#ff6b6b',
  'Cordova': '#ffb13b',
  'Ionic': '#4285f4',
  'Flutter': '#00d4aa',
  'React Native': '#ff6b35',
  'Tauri': '#4285f4',
  'Electron': '#00d4aa',
  'WebRTC': '#ff6b6b',
  'WebSocket': '#ffb13b',
  'gRPC': '#4285f4',
  'GraphQL': '#00d4aa',
  'REST': '#ff6b35',
  'API': '#4285f4',
  'SSG': '#00d4aa',
  'SSR': '#ff6b6b',
  'SPA': '#ffb13b',
  'PWA': '#4285f4',
  'Serverless': '#00d4aa',
  'Microservices': '#ff6b35',
  'Monorepo': '#4285f4',
  'Turborepo': '#00d4aa',
  'Nx': '#ff6b6b',
  'Rush': '#ffb13b',
  'Lerna': '#4285f4',
  'pnpm': '#00d4aa',
  'Yarn': '#ff6b35',
  'npm': '#4285f4',
  'Bitbucket Pipelines': '#00d4aa',
  'GitLab CI': '#ff6b6b',
  'Jenkins': '#ffb13b',
  'CircleCI': '#4285f4',
  'Travis CI': '#00d4aa',
  'GitHub Actions': '#ff6b35',
  'DigitalOcean': '#4285f4',
  'Heroku': '#00d4aa',
  'Netlify': '#ff6b6b',
  'Vercel': '#ffb13b',
  'Firebase': '#4285f4',
  'Google Cloud': '#00d4aa',
  'Azure': '#ff6b35',
  'AWS': '#4285f4',
  'Kubernetes': '#00d4aa',
  'Docker': '#ff6b6b',
  'Redis': '#ffb13b',
  'SQLite': '#4285f4',
  'MySQL': '#00d4aa',
  'PostgreSQL': '#ff6b35',
  'MongoDB': '#4285f4',
  'Prisma': '#00d4aa',
  'Apollo': '#ff6b6b',
  'GraphQL': '#ffb13b',
  'PostCSS': '#4285f4',
  'Less': '#00d4aa',
  'Sass': '#ff6b35',
  'Styled Components': '#4285f4',
  'Chakra UI': '#00d4aa',
  'Ant Design': '#ff6b6b',
  'Material-UI': '#ffb13b',
  'Bootstrap': '#4285f4',
  'Tailwind CSS': '#00d4aa',
  'Storybook': '#ff6b35',
  'Cypress': '#4285f4',
  'Jest': '#00d4aa',
  'Prettier': '#ff6b6b',
  'ESLint': '#ffb13b',
  'Babel': '#4285f4',
  'Webpack': '#00d4aa',
  'Vite': '#ff6b35',
  'Nuxt.js': '#4285f4',
  'Next.js': '#00d4aa',
  'Svelte': '#ff6b6b',
  'Angular': '#ffb13b',
  'React': '#4285f4',
  'Vue': '#00d4aa',
  'Assembly': '#ff6b35',
  'F#': '#4285f4',
  'OCaml': '#00d4aa',
  'Haskell': '#ff6b6b',
  'Clojure': '#ffb13b',
  'Elixir': '#4285f4',
  'Dart': '#00d4aa',
  'Lua': '#ff6b35',
  'PowerShell': '#4285f4',
  'Shell': '#00d4aa',
  'MATLAB': '#ff6b6b',
  'R': '#ffb13b',
  'Scala': '#4285f4',
  'Kotlin': '#00d4aa',
  'Swift': '#ff6b35',
  'Rust': '#4285f4',
  'Go': '#00d4aa',
  'Ruby': '#ff6b6b',
  'PHP': '#ffb13b',
  'C': '#4285f4',
  'C++': '#00d4aa',
  'C#': '#ff6b35',
  'Java': '#4285f4',
  'Python': '#00d4aa',
  'CSS': '#ff6b6b',
  'HTML': '#ffb13b',
  'JavaScript': '#4285f4',
  'TypeScript': '#00d4aa'
};

export const getLanguageColor = (language: string): string => {
  return languageColors[language] || '#6e7781'; // Default GitHub gray
};

// Common programming languages that might appear in repository topics
export const commonLanguages = [
  'TypeScript', 'JavaScript', 'HTML', 'CSS', 'Python', 'Java', 'C#', 'C++', 'C',
  'PHP', 'Ruby', 'Go', 'Rust', 'Swift', 'Kotlin', 'Scala', 'R', 'MATLAB', 'Shell',
  'PowerShell', 'Lua', 'Dart', 'Elixir', 'Clojure', 'Haskell', 'OCaml', 'F#',
  'Assembly', 'Vue', 'React', 'Angular', 'Svelte', 'Next.js', 'Nuxt.js', 'Vite',
  'Webpack', 'Babel', 'ESLint', 'Prettier', 'Jest', 'Cypress', 'Storybook',
  'Tailwind CSS', 'Bootstrap', 'Material-UI', 'Ant Design', 'Chakra UI',
  'Styled Components', 'Sass', 'Less', 'PostCSS', 'GraphQL', 'Apollo', 'Prisma',
  'MongoDB', 'PostgreSQL', 'MySQL', 'SQLite', 'Redis', 'Docker', 'Kubernetes',
  'AWS', 'Azure', 'Google Cloud', 'Firebase', 'Vercel', 'Netlify', 'Heroku',
  'DigitalOcean', 'GitHub Actions', 'Travis CI', 'CircleCI', 'Jenkins',
  'GitLab CI', 'Bitbucket Pipelines', 'npm', 'Yarn', 'pnpm', 'Lerna', 'Rush',
  'Nx', 'Turborepo', 'Monorepo', 'Microservices', 'Serverless', 'JAMstack',
  'PWA', 'SPA', 'SSR', 'SSG', 'API', 'REST', 'gRPC', 'WebSocket', 'WebRTC',
  'Electron', 'Tauri', 'React Native', 'Flutter', 'Ionic', 'Cordova', 'Capacitor',
  'Unity', 'Unreal Engine', 'Godot', 'Blender', 'Three.js', 'WebGL', 'Canvas',
  'SVG', 'Web Audio', 'Web Workers', 'Service Workers', 'IndexedDB', 'LocalStorage',
  'SessionStorage', 'Cookies', 'JWT', 'OAuth', 'OpenID Connect', 'SAML', 'LDAP',
  'Active Directory', 'OAuth 2.0', 'OIDC', 'SAML 2.0', 'SCIM', 'MFA', '2FA',
  'TOTP', 'HOTP', 'U2F', 'WebAuthn', 'FIDO2', 'Biometric', 'Face ID', 'Touch ID',
  'Fingerprint', 'Iris', 'Voice', 'Behavioral', 'Risk-based', 'Adaptive',
  'Contextual', 'Zero Trust', 'Zero Knowledge', 'End-to-End', 'Client-Side',
  'Server-Side', 'Edge', 'Cloud', 'Hybrid', 'Multi-Cloud', 'Polyglot',
  'Micro-Frontends', 'Module Federation', 'Web Components', 'Custom Elements',
  'Shadow DOM', 'HTML Templates', 'Progressive Enhancement', 'Graceful Degradation',
  'Feature Detection', 'Polyfills', 'Shims', 'Fallbacks', 'Graceful Fallbacks',
  'Elegant Degradation', 'Responsive Design', 'Mobile First', 'Desktop First',
  'Adaptive Design', 'Fluid Design', 'Elastic Design', 'Liquid Design',
  'Fixed Design', 'Hybrid Design', 'Atomic Design', 'Design Systems',
  'Component Libraries', 'UI Kits', 'Design Tokens', 'Style Guides',
  'Brand Guidelines', 'Visual Identity', 'Brand Identity', 'Corporate Identity',
  'Brand Strategy', 'Brand Positioning', 'Brand Architecture', 'Brand Portfolio',
  'Brand Extension', 'Brand Dilution', 'Brand Equity', 'Brand Value',
  'Brand Recognition', 'Brand Recall', 'Brand Awareness', 'Brand Loyalty',
  'Brand Trust', 'Brand Reputation', 'Brand Image', 'Brand Personality',
  'Brand Voice', 'Brand Tone', 'Brand Messaging', 'Brand Communication',
  'Brand Marketing', 'Brand Advertising', 'Brand Promotion', 'Brand Publicity',
  'Brand PR', 'Brand Media', 'Brand Content', 'Brand Storytelling',
  'Brand Narrative', 'Brand Story', 'Brand Journey', 'Brand Experience',
  'Brand Touchpoints', 'Brand Interactions', 'Brand Engagement', 'Brand Activation',
  'Brand Events', 'Brand Sponsorships', 'Brand Partnerships', 'Brand Collaborations',
  'Brand Co-branding', 'Brand Franchising', 'Brand Expansion', 'Brand Growth',
  'Brand Development', 'Brand Evolution', 'Brand Transformation', 'Brand Rebranding',
  'Brand Refresh', 'Brand Update', 'Brand Modernization', 'Brand Innovation',
  'Brand Disruption', 'Brand Revolution'
];

// Extract languages from repository topics and primary language
export const extractLanguagesFromRepo = (repo: { language: string | null; topics: string[] }): string[] => {
  const languages = new Set<string>();
  
  // Add primary language if it exists
  if (repo.language) {
    languages.add(repo.language);
  }
  
  // Add languages from topics
  repo.topics.forEach(topic => {
    if (commonLanguages.includes(topic)) {
      languages.add(topic);
    }
  });
  
  return Array.from(languages);
};
